-- Olenix menu seed — generated from printed menus. Run after 001–005.
delete from public.menu;
delete from public.menu_categories;

insert into public.menu_categories (id, name, image_url) values
  ('cognac', 'Cognac', ''),
  ('whiskey-brandy', 'Whiskey & Brandy', ''),
  ('wine', 'Wine', ''),
  ('tequila', 'Tequila', ''),
  ('champagne', 'Champagne', ''),
  ('spirit-vodka', 'Spirit & Vodka', ''),
  ('premium-additions', 'Premium Additions', ''),
  ('herbs-drinks', 'Herbs Drinks', ''),
  ('energy', 'Energy', ''),
  ('beer', 'Beer', ''),
  ('cigarette', 'Cigarette', ''),
  ('shorts-drinks', 'Shorts Drinks', ''),
  ('juice-soft-drink', 'Juice / Soft Drink', ''),
  ('shisha', 'Shisha', ''),
  ('sides', 'Sides', ''),
  ('special-soup', 'Special Soup', ''),
  ('rice', 'Rice', ''),
  ('special-rice', 'Special Rice', ''),
  ('platter', 'Platter', ''),
  ('olenix-combo', 'Olenix Combo', ''),
  ('olenix-chops', 'Olenix Chops', ''),
  ('olenix-mini-combo', 'Olenix Mini Combo', ''),
  ('olenix-king-size-combo', 'Olenix King Size Combo', ''),
  ('pasta-corner', 'Pasta Corner', ''),
  ('swallows', 'Swallows', ''),
  ('native-corner', 'Native Corner', ''),
  ('bites-corners', 'Bites Corners', ''),
  ('soups', 'Soups', ''),
  ('fish-seafood', 'Fish & Seafood', ''),
  ('jumbo-prawns', 'Jumbo Prawns', ''),
  ('olenix-creamy-pasta', 'Olenix Creamy Pasta', ''),
  ('grills', 'Grills', ''),
  ('pepper-soups', 'Pepper Soups', ''),
  ('seafood-corner', 'Sea Food Corner', '');

insert into public.menu (category, name, price, description) values
  ('Cognac', 'Martel Swift', '₦140,000', ''),
  ('Cognac', 'Martel VS', '₦90,000', ''),
  ('Cognac', 'Martel XO', '₦400,000', ''),
  ('Cognac', 'Hennessy VS', '₦90,000', ''),
  ('Cognac', 'Hennessy VSOP', '₦140,000', ''),
  ('Cognac', 'Hennessy XO', '₦400,000', ''),
  ('Cognac', 'Remy Martins', '₦150,000', ''),
  ('Cognac', 'Lise (B) VSOP', '₦100,000', ''),
  ('Cognac', 'Lise (B) Cocktail', '₦70,000', ''),
  ('Cognac', 'Lise (B) Fine Cognac', '₦85,000', ''),
  ('Whiskey & Brandy', 'Glenfiddich 18 Years', '₦180,000', ''),
  ('Whiskey & Brandy', 'Glenfiddich 12 Years', '₦90,000', ''),
  ('Whiskey & Brandy', 'Glenfiddich 15 Years', '₦140,000', ''),
  ('Whiskey & Brandy', 'Singleton 12 Years', '₦100,000', ''),
  ('Whiskey & Brandy', 'Singleton 15 Years', '₦145,000', ''),
  ('Whiskey & Brandy', 'Jameson Black', '₦70,000', ''),
  ('Whiskey & Brandy', 'Jameson Green', '₦45,000', ''),
  ('Whiskey & Brandy', 'Jack Daniel', '₦40,000', ''),
  ('Whiskey & Brandy', 'Observatory', '₦70,000', ''),
  ('Whiskey & Brandy', 'Monkey Shoulder', '₦80,000', ''),
  ('Whiskey & Brandy', 'Artesnes', '₦40,000', ''),
  ('Whiskey & Brandy', 'William Lawson', '₦35,000', ''),
  ('Whiskey & Brandy', 'William Lawson SM', '₦10,000', ''),
  ('Whiskey & Brandy', 'Red Label', '₦35,000', ''),
  ('Whiskey & Brandy', 'Tullamore', '₦45,000', ''),
  ('Whiskey & Brandy', 'Viecchia', '₦75,000', ''),
  ('Whiskey & Brandy', 'Grants', '₦40,000', ''),
  ('Whiskey & Brandy', 'Campari (B)', '₦35,000', ''),
  ('Whiskey & Brandy', 'Campari (M)', '₦25,000', ''),
  ('Whiskey & Brandy', 'Campari (S)', '₦10,000', ''),
  ('Wine', '4 Cousins', '₦20,000', ''),
  ('Wine', 'Carlo Rossi', '₦25,000', ''),
  ('Wine', 'Asconi Agor', '₦25,000', ''),
  ('Wine', 'Escudo Rojo', '₦35,000', ''),
  ('Wine', 'Expression', '₦35,000', ''),
  ('Wine', 'Fidossi Red Wine', '₦35,000', ''),
  ('Wine', 'Lambrusco', '₦35,000', ''),
  ('Wine', 'Castillo Grande', '₦20,000', ''),
  ('Wine', 'Sweet Kiss Red/Rose', '₦25,000', ''),
  ('Wine', 'Festa Wine Red/Rose', '₦25,000', ''),
  ('Wine', 'Declao 4th Street Wine', '₦25,000', ''),
  ('Wine', 'Henkel Piccolo', '₦30,000', ''),
  ('Wine', 'Schoenaich Wine', '₦30,000', ''),
  ('Wine', 'Le-Filou', '₦30,000', ''),
  ('Wine', 'Chewaraze Merlot', '₦30,000', ''),
  ('Wine', 'Les Vignerons', '₦30,000', ''),
  ('Wine', 'Cheval d''Elena Edward''s Wine', '₦30,000', ''),
  ('Wine', 'Wein', '₦30,000', ''),
  ('Wine', 'Rot Wein', '₦30,000', ''),
  ('Wine', 'Stettyn Red Wine', '₦25,000', ''),
  ('Wine', 'Stettyn Sweet Wine', '₦25,000', ''),
  ('Wine', 'Cartier Wine (S)', '₦6,000', ''),
  ('Wine', 'Babelki C', '₦30,000', ''),
  ('Tequila', 'Sierra White', '₦30,000', ''),
  ('Tequila', 'Casamigo', '₦200,000', ''),
  ('Tequila', 'Sierra Gold', '₦35,000', ''),
  ('Tequila', 'Sierra Tropical', '₦35,000', ''),
  ('Tequila', 'Olmeca', '₦45,000', ''),
  ('Tequila', 'Agavales', '₦30,000', ''),
  ('Tequila', 'Bacardi White/Gold', '₦30,000', ''),
  ('Champagne', 'Belaire Rose', '₦80,000', ''),
  ('Champagne', 'Moet Rose', '₦150,000', ''),
  ('Champagne', 'Moet Ice', '₦150,000', ''),
  ('Champagne', 'Martini Rose', '₦30,000', ''),
  ('Champagne', 'Mood', '₦65,000', ''),
  ('Champagne', 'Moet Chandon', '₦150,000', ''),
  ('Spirit & Vodka', 'Belvedere Big', '₦90,000', ''),
  ('Spirit & Vodka', 'Belvedere Medium', '₦70,000', ''),
  ('Spirit & Vodka', 'Best Vodka Big', '₦15,000', ''),
  ('Spirit & Vodka', 'Best Vodka Small', '₦6,000', ''),
  ('Spirit & Vodka', 'Best VIP', '₦15,000', ''),
  ('Spirit & Vodka', 'Best VIP Small', '₦6,000', ''),
  ('Spirit & Vodka', 'Best Inferno Big', '₦15,000', ''),
  ('Spirit & Vodka', 'Best Inferno Small', '₦6,000', ''),
  ('Spirit & Vodka', 'Best Cream Big', '₦15,000', ''),
  ('Spirit & Vodka', 'Best Cream Small', '₦6,000', ''),
  ('Spirit & Vodka', 'Don Coco', '₦2,000', ''),
  ('Spirit & Vodka', 'Best Dry Gin Big', '₦15,000', ''),
  ('Spirit & Vodka', 'Best Whisky Big', '₦15,000', ''),
  ('Spirit & Vodka', 'Best Whisky Small', '₦6,000', ''),
  ('Spirit & Vodka', 'Gordon''s', '₦15,000', ''),
  ('Spirit & Vodka', 'Magic Moment', '₦6,000', ''),
  ('Spirit & Vodka', 'Smirnoff Vodka X1', '₦15,000', ''),
  ('Spirit & Vodka', 'Smirnoff 100 Quality', '₦10,000', ''),
  ('Spirit & Vodka', 'Smirnoff Ice Gin Medium', '₦8,000', ''),
  ('Spirit & Vodka', 'Smirnoff Ice Gin Small', '₦6,000', ''),
  ('Spirit & Vodka', 'Jagermeister', '₦45,000', ''),
  ('Spirit & Vodka', 'Gordon''s Small', '₦6,000', ''),
  ('Spirit & Vodka', 'Gordon''s Medium', '₦8,000', ''),
  ('Premium Additions', '1960 Root', '₦15,000', ''),
  ('Premium Additions', 'American Honey', '₦40,000', ''),
  ('Premium Additions', 'Declan', '₦20,000', ''),
  ('Premium Additions', 'Cooper & Thief', '₦80,000', ''),
  ('Premium Additions', 'Remy Martins', '₦150,000', ''),
  ('Herbs Drinks', 'Origin Plastic', '₦2,500', ''),
  ('Herbs Drinks', 'Actiona Bitter', '₦2,500', ''),
  ('Herbs Drinks', 'Odogwu Bitter', '₦2,000', ''),
  ('Herbs Drinks', 'De General', '₦2,000', ''),
  ('Herbs Drinks', 'Long Jack', '₦2,000', ''),
  ('Herbs Drinks', 'Ace Bitters', '₦2,000', ''),
  ('Energy', 'Amber', '₦2,000', ''),
  ('Energy', 'Fearless Pet', '₦1,000', ''),
  ('Energy', 'Fearless Can', '₦1,000', ''),
  ('Energy', 'Predator', '₦1,000', ''),
  ('Energy', 'Monster', '₦2,000', ''),
  ('Energy', 'Bullet', '₦3,000', ''),
  ('Energy', 'Red Bull', '₦3,000', ''),
  ('Energy', 'Power House', '₦3,000', ''),
  ('Beer', 'Big Heineken', '₦2,500', ''),
  ('Beer', 'Medium Heineken', '₦2,000', ''),
  ('Beer', 'Big Stout', '₦2,500', ''),
  ('Beer', 'Small Stout', '₦2,000', ''),
  ('Beer', 'Goldberg', '₦2,000', ''),
  ('Beer', 'Gulder', '₦2,500', ''),
  ('Beer', 'Life', '₦2,000', ''),
  ('Beer', '33 Expert', '₦2,000', ''),
  ('Beer', 'Legend', '₦2,000', ''),
  ('Beer', 'Turbo King', '₦2,000', ''),
  ('Beer', 'Tiger', '₦1,500', ''),
  ('Beer', 'Despirado', '₦2,000', ''),
  ('Beer', 'Star', '₦2,000', ''),
  ('Beer', 'Castle Light Can', '₦2,000', ''),
  ('Beer', 'Goldberg Black Big', '₦2,000', ''),
  ('Beer', 'Star Radler', '₦2,000', ''),
  ('Beer', 'Origin Beer', '₦2,000', ''),
  ('Beer', 'Trophy', '₦2,000', ''),
  ('Beer', 'Trophy Stout', '₦2,000', ''),
  ('Beer', 'Budweiser', '₦2,000', ''),
  ('Beer', 'Budweiser Royale', '₦2,500', ''),
  ('Beer', 'Castle Lite', '₦2,000', ''),
  ('Beer', 'Hero', '₦2,000', ''),
  ('Beer', 'Flying Fish', '₦2,000', ''),
  ('Beer', 'Double Black', '₦2,000', ''),
  ('Beer', 'Smirnoff Ice Bottle', '₦2,000', ''),
  ('Beer', 'Smirnoff Can', '₦2,000', ''),
  ('Beer', 'Smirnoff Double Blk', '₦2,000', ''),
  ('Beer', 'Smirnoff Ice Big', '₦2,500', ''),
  ('Beer', 'Goldberg Black Small', '₦1,500', ''),
  ('Cigarette', 'Benson Brown', '₦2,500', ''),
  ('Cigarette', 'Benson Switch', '₦2,500', ''),
  ('Cigarette', 'Rothmans', '₦2,500', ''),
  ('Cigarette', 'Chesterfield', '₦2,500', ''),
  ('Cigarette', 'Dunhill', '₦2,500', ''),
  ('Cigarette', 'Esse Change', '₦2,500', ''),
  ('Cigarette', 'Bohem', '₦2,500', ''),
  ('Cigarette', 'Lighter', '₦500', ''),
  ('Shorts Drinks', 'Sierra Shots', '₦3,000', ''),
  ('Shorts Drinks', 'Olmeca Shot', '₦3,000', ''),
  ('Shorts Drinks', 'Agavales Shot', '₦3,000', ''),
  ('Shorts Drinks', 'Bacardi Shot', '₦3,000', ''),
  ('Shorts Drinks', 'Gordon''s Shot', '₦2,000', ''),
  ('Juice / Soft Drink', 'Maltina Bottle', '₦1,500', ''),
  ('Juice / Soft Drink', 'Maltina Can', '₦1,500', ''),
  ('Juice / Soft Drink', 'Malta Guinness', '₦1,500', ''),
  ('Juice / Soft Drink', 'Vita Milk', '₦2,500', ''),
  ('Juice / Soft Drink', 'Fayrouz', '₦1,000', ''),
  ('Juice / Soft Drink', 'Coke', '₦1,000', ''),
  ('Juice / Soft Drink', 'Fanta', '₦1,000', ''),
  ('Juice / Soft Drink', 'Pepsi', '₦1,000', ''),
  ('Juice / Soft Drink', 'Sprite', '₦1,000', ''),
  ('Juice / Soft Drink', 'Water (Aquatina)', '₦500', ''),
  ('Juice / Soft Drink', 'Amstel Malt', '₦1,500', ''),
  ('Juice / Soft Drink', 'Water (Eva)', '₦500', ''),
  ('Juice / Soft Drink', 'Schweppes', '₦1,000', ''),
  ('Juice / Soft Drink', 'Teem', '₦1,000', ''),
  ('Juice / Soft Drink', '7UP', '₦1,000', ''),
  ('Juice / Soft Drink', '5 Alives Big', '₦3,000', ''),
  ('Juice / Soft Drink', '5 Alives Small', '₦1,000', ''),
  ('Juice / Soft Drink', 'Hollandia', '₦3,000', ''),
  ('Juice / Soft Drink', 'Exotic', '₦3,000', ''),
  ('Juice / Soft Drink', 'Chivita', '₦3,500', ''),
  ('Shisha', 'Shisha', '₦10,000', ''),
  ('Sides', 'Tomato Sauce', '₦3,000', ''),
  ('Sides', 'Salad', '₦2,000', ''),
  ('Sides', 'Okra Special', '₦5,000', ''),
  ('Special Soup', 'Fisherman Soup', '₦30,000', ''),
  ('Special Soup', 'Seafood Okra', '₦30,000', ''),
  ('Special Soup', 'White Soup', '₦15,000', ''),
  ('Rice', 'Jollof Rice', '₦4,000', ''),
  ('Rice', 'Coconut Rice', '₦5,000', ''),
  ('Rice', 'White Rice', '₦3,000', ''),
  ('Rice', 'Fried Rice', '₦5,000', ''),
  ('Special Rice', 'Asun Rice', '₦10,000', ''),
  ('Special Rice', 'Chinese Rice', '₦10,000', ''),
  ('Special Rice', 'Pineapple Rice', '₦10,000', ''),
  ('Special Rice', 'Special Olenix Fried Rice', '₦15,000', ''),
  ('Special Rice', 'Native Rice', '₦7,000', ''),
  ('Platter', 'Spacial Olenix Sea Platter', '₦35,000', 'Prawns, crab, snail, spring rolls, samosa, puff puff, yam chips, potato chips, sauce, salad'),
  ('Olenix Combo', 'Olenix Combo', '₦30,000', 'Gizzard, spring rolls, samosa, puff puff, yam chips, potato chips, chicken wings, sauce and salad'),
  ('Olenix Chops', 'Olenix Chops', '₦10,000', 'Spring rolls, samosa, puff puff'),
  ('Olenix Mini Combo', 'Olenix Mini Combo', '₦18,000', 'Samosa, spring rolls, puff puff, chicken'),
  ('Olenix King Size Combo', 'Olenix King Size Combo', '₦60,000', 'Prawns, snail, crab, wings, gizzard, fried rice, samosa, spring rolls, puff puff, yam chips, potato chips, salad, sauce'),
  ('Pasta Corner', 'Jollof Spaghetti', '₦5,000', ''),
  ('Pasta Corner', 'Stir Fry Spaghetti', '₦5,000', ''),
  ('Pasta Corner', 'Spaghetti Bolongese', '₦10,000', ''),
  ('Pasta Corner', 'Spaghetti Cabonara', '₦10,000', ''),
  ('Pasta Corner', 'Indomie and Eggs', '₦4,000', ''),
  ('Pasta Corner', 'Singapore Noodle', '₦15,000', ''),
  ('Pasta Corner', 'Yam Porridge', '₦6,000', ''),
  ('Pasta Corner', 'Yam and Egg Sauce', '₦6,000', ''),
  ('Pasta Corner', 'Yam Chips', '₦3,000', ''),
  ('Pasta Corner', 'Potato Chips', '₦2,000', ''),
  ('Pasta Corner', 'Sausage', '₦1,000', ''),
  ('Pasta Corner', 'Gizdodo', '₦10,000', ''),
  ('Pasta Corner', 'Yamarita', '₦6,000', ''),
  ('Pasta Corner', 'Plantain', '₦2,000', ''),
  ('Pasta Corner', 'Plantain Porridge', '₦6,000', ''),
  ('Swallows', 'Poundo', '₦3,000', ''),
  ('Swallows', 'Semo', '₦2,000', ''),
  ('Swallows', 'Eba', '₦2,000', ''),
  ('Swallows', 'Starch', '₦3,000', ''),
  ('Swallows', 'Wheat', '₦2,000', ''),
  ('Native Corner', 'Isi Ewu', '₦15,000', ''),
  ('Native Corner', 'Nkwobi', '₦7,000', ''),
  ('Native Corner', 'Asun', '₦5,000', ''),
  ('Bites Corners', 'Shawarma (2 Sauage)', '₦5,000', ''),
  ('Bites Corners', 'Chicken and Chips (Potato)', '₦8,000', ''),
  ('Bites Corners', 'Chicken and Yam', '₦9,000', ''),
  ('Bites Corners', 'Spring Rolls', '₦3,500', ''),
  ('Bites Corners', 'Samosa', '₦3,500', ''),
  ('Bites Corners', 'Puff Puff', '₦3,000', ''),
  ('Bites Corners', 'Shrimps Spring Rolls', '₦5,000', ''),
  ('Bites Corners', 'Fish Sauce', '₦9,000', ''),
  ('Bites Corners', 'Vegetable Sauce', '₦3,000', ''),
  ('Soups', 'Afang Soup', '₦3,000', ''),
  ('Soups', 'Oha Soup', '₦3,000', ''),
  ('Soups', 'Okra Soup', '₦3,000', ''),
  ('Soups', 'Egusi Soup', '₦3,000', ''),
  ('Soups', 'Ogbono Soup', '₦3,000', ''),
  ('Soups', 'Vegetable Soup', '₦3,000', ''),
  ('Soups', 'Bitter Leaf Soup', '₦3,000', ''),
  ('Soups', 'Banga Soup', '₦4,000', ''),
  ('Soups', 'Stew', '₦3,000', ''),
  ('Soups', 'Pepper Soup', '₦3,000', ''),
  ('Soups', 'White Soup (Snela)', '₦5,000', ''),
  ('Fish & Seafood', 'Assorted', '₦5,000', ''),
  ('Fish & Seafood', 'Dried Catfish', '₦5,000', ''),
  ('Fish & Seafood', 'Big Dried Catfish', '₦10,000', ''),
  ('Fish & Seafood', 'Turkey', '₦9,000', ''),
  ('Fish & Seafood', 'Prawns', '₦10,000', ''),
  ('Fish & Seafood', 'Croacker (₦25,000)', '₦25,000', ''),
  ('Fish & Seafood', 'Croacker (₦22,000)', '₦22,000', ''),
  ('Fish & Seafood', 'Croacker (₦18,000)', '₦18,000', ''),
  ('Fish & Seafood', 'Croacker (₦15,000)', '₦15,000', ''),
  ('Jumbo Prawns', 'White — Choice of Chips / Jollof Rice / Fried Rice', '₦15,000', ''),
  ('Olenix Creamy Pasta', 'Shrimps / Chicken', '₦15,000', ''),
  ('Grills', 'Big Barbecue Fish', '₦25,000', ''),
  ('Grills', 'Medium Barbecue', '₦22,000', ''),
  ('Grills', 'Roasted Plantain', '₦3,000', ''),
  ('Pepper Soups', 'Goat Meat Pepper Soup', '₦6,000', ''),
  ('Pepper Soups', 'Chicken Pepper Soup', '₦7,000', ''),
  ('Pepper Soups', 'Turkey Pepper Soup', '₦9,000', ''),
  ('Pepper Soups', 'Assorted Pepper Soup', '₦5,000', ''),
  ('Pepper Soups', 'Full Catfish Pepper Soup (Big)', '₦25,000', ''),
  ('Pepper Soups', 'Full Catfish Pepper Soup (Medium)', '₦22,000', ''),
  ('Pepper Soups', 'Cut Fish', '₦6,000', ''),
  ('Pepper Soups', 'Beef Pepper Soup', '₦6,000', ''),
  ('Pepper Soups', 'Cut Croacker Fish', '₦7,000', ''),
  ('Sea Food Corner', 'Snail Jumbo Size', '₦9,000', ''),
  ('Sea Food Corner', 'Crab', '₦2,000', ''),
  ('Sea Food Corner', 'Big Prawns', '₦10,000', ''),
  ('Sea Food Corner', 'Small Prawns', '₦7,000', ''),
  ('Sea Food Corner', 'Shrimps', '₦10,000', ''),
  ('Sea Food Corner', 'Prawns Pepper Soup', '₦15,000', '');

notify pgrst, 'reload schema';
