-- admins.id MUST be the Supabase Auth user UUID (auth.users.id).
-- Do NOT set a default on id — autogenerated IDs break login and RLS.
--
-- Correct flow:
--   1. Create user in Supabase Auth (with email + password), OR use /admin/staff in the app
--   2. Insert into admins using that user's UUID as id

-- Remove autogenerate default if it was added in the Dashboard
alter table public.admins alter column id drop default;

-- Re-attach foreign key to auth.users (safe if already exists)
alter table public.admins drop constraint if exists admins_id_fkey;
alter table public.admins
  add constraint admins_id_fkey
  foreign key (id) references auth.users (id) on delete cascade;

-- Reject admin rows that don't match a real Auth user
create or replace function public.add_admin_record(
  p_user_id text,
  p_email text,
  p_role text default 'admin'
)
returns json
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_super_admin() then
    return json_build_object('ok', false, 'error', 'unauthorized');
  end if;

  if p_role is distinct from 'admin' then
    return json_build_object('ok', false, 'error', 'super_admin_via_supabase_only');
  end if;

  if not exists (select 1 from auth.users where id = p_user_id::uuid) then
    return json_build_object(
      'ok', false,
      'error', 'auth_user_not_found',
      'hint', 'Create the user in Supabase Auth first (with a password), then link their UUID here.'
    );
  end if;

  insert into public.admins (id, email, role)
  values (p_user_id::uuid, lower(trim(p_email)), 'admin')
  on conflict (id) do update
    set email = excluded.email,
        role = 'admin';

  return json_build_object('ok', true, 'id', p_user_id);
end;
$$;

grant execute on function public.add_admin_record(text, text, text) to authenticated;

notify pgrst, 'reload schema';
